global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'db_metrics'
    static_configs:
      - targets: ['database:6989']
  - job_name: 'docker_custom_exporter'
    static_configs:
      - targets: ['docker_custom_exporter:6789']
  - job_name: 'server'
    static_configs:
      - targets: ['server:3000']

rule_files:
  - "./rules/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alert_manager:9093'

# data exporters = petits programmes qui transforment les metriques d'une appli en format comprehensible par prometheus
# integration = config de prometheus pour aller chercher les donnees de ces exporters via leurs endpoints

# docker containers = cAdvisor
# sqlite3 = exporter custom
# server = exporter custom
# linux/VM system stats = node_exporter



# TODO:
#  ajouter alerts en cas de metrics down (pas d'acces a l'endpoint)